name: climaX
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asciitree=0.3.3=py_2
  - blas=1.0=mkl
  - bokeh=2.4.3=pyhd8ed1ab_3
  - bottleneck=1.3.6=py38h7e4f40d_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cf_xarray=0.7.9=pyhd8ed1ab_0
  - cffi=1.15.1=py38h5eee18b_3
  - cftime=1.6.2=py38h26c90d9_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - cryptography=38.0.4=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.87.0=h6312ad2_0
  - cytoolz=0.12.0=py38h0a891b7_1
  - dask=2023.1.1=pyhd8ed1ab_0
  - dask-core=2023.1.1=pyhd8ed1ab_0
  - distributed=2023.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - esmf=8.4.0=nompi_hdb2cfa9_3
  - esmpy=8.4.0=nompi_py38h2b78397_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - geos=3.11.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.2=nompi_h2386368_101
  - heapdict=1.0.1=py_0
  - idna=3.4=py38h06a4308_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h7f8727e_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.6=hcb278e6_1
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libllvm11=11.1.0=he0ac6c6_5
  - libnetcdf=4.8.1=nompi_h21705cb_104
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=h6a678d5_1
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libzip=1.9.2=hc869a4a_1
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.39.1=py38h38d86a4_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.2.0=py38hd012fdc_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.2=py38h1de0b5d_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - msgpack-python=1.0.4=py38h43d8883_1
  - ncurses=6.4=h6a678d5_0
  - netcdf-fortran=4.6.0=nompi_he1eeb6f_102
  - netcdf4=1.6.2=nompi_py38h2250339_100
  - nettle=3.7.3=hbbd107a_1
  - numba=0.56.4=py38h9a4aae9_0
  - numcodecs=0.11.0=py38h8dc9893_1
  - numpy=1.23.5=py38h14f4228_0
  - numpy-base=1.23.5=py38h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h0b41bf4_1
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py38hdc8b05c_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pillow=9.3.0=py38h6a678d5_2
  - pip=22.3.1=py38h06a4308_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - portalocker=2.3.0=py38h06a4308_0
  - psutil=5.9.4=py38h0a891b7_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.16=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyyaml=6.0=py38h0a891b7_5
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py38h06a4308_0
  - scipy=1.10.0=py38h14f4228_0
  - setuptools=65.6.3=py38h06a4308_0
  - shapely=1.8.5=py38hafd38ec_2
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sparse=0.13.0=pyhd8ed1ab_0
  - sqlite=3.40.1=h5082296_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - torchaudio=0.12.1=py38_cu113
  - torchdata=0.4.1=py38
  - torchvision=0.13.1=py38_cu113
  - tornado=6.2=py38h0a891b7_1
  - typing_extensions=4.4.0=py38h06a4308_0
  - urllib3=1.26.14=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xarray=2023.1.0=pyhd8ed1ab_0
  - xesmf=0.7.0=pyhd8ed1ab_0
  - xz=5.2.10=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - zarr=2.13.6=pyhd8ed1ab_0
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.12.1=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - absl-py==1.4.0
      - aiohttp==3.8.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.2
      - attrs==22.2.0
      - cachetools==5.3.0
      - docstring-parser==0.15
      - einops==0.6.0
      - filelock==3.9.0
      - fire==0.5.0
      - frozenlist==1.3.3
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.52.0
      - huggingface-hub==0.12.0
      - importlib-resources==5.10.2
      - jsonargparse==4.19.0
      - lightning-lite==1.8.0
      - lightning-utilities==0.3.0
      - markdown==3.4.1
      - multidict==6.0.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pytorch-lightning==1.8.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.2.0
      - timm==0.6.12
      - torchmetrics==0.11.1
      - tqdm==4.64.1
      - typeshed-client==2.2.0
      - werkzeug==2.2.2
      - yarl==1.8.2
